### ISSUE TITLE
File Save Error (Invalid response: 413) for notebooks >1M in size 

### ISSUE THREAD

**Issue by tylere** [nds-org/esiphub#18]
The ESIPHub JupyterHub appears to have a very restrictive limit of 1M for file size.

![image](https://user-images.githubusercontent.com/92862/42714974-c7114d88-86a9-11e8-94d8-d3da203a674b.png)

This issue can be reproduced by running a notebook and then attempting to save it (or wait for the autosave to happen).

**Comment by tylere** [comment]
Potentially relevant issues/PRs:
- [Allow setting a custom max body size in nginx proxy](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/346)

**Comment by tylere** [comment]
Here is a much simpler example that triggers the error:


```
from IPython.display import Image

for i in range(20):
    display(Image(
        url='http://www.esipfed.org/wp-content/uploads/2017/11/2018_Meeting_Branding_FullV2_RGB@1x.png',
        embed=True,
        format='png'
    ))
```

**Comment by scgordon** [comment]
confirm error 413 with test.

**Comment by scgordon** [comment]
Further file testing:
I can upload a file from my computer to my instance that is < 15M
I can create and save a file that is > 35M (not sure the upper limit)
but I cannot save a Notebook > 1

**Comment by craig-willis** [comment]
@tylere Sorry for the late response.  You are correct that this is related to the nginx proxy body size.  Will update the configuration and let you know when resolved.

**Comment by craig-willis** [comment]
I've updated the the nginx configmap setting `proxy-body-size: 64m` per the above PR and restarted the ingress pods. Your test case is now working for me. Let me know if otherwise.

**Comment by craig-willis** [comment]
Closing this based, but noting based on https://gitter.im/jupyterhub/jupyterhub?at=5b68936dc917d40dc24e4305

I implemented the change in the nginx ILB configmap directly, but apparently could've been achieved through the JupyterHub configuration:
```
  ingress:
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
```

I didn't need to change the proxy body size, since it is already 64m.
```
hub:
  nginx:
    proxyBodySize: 64m
```
