### ISSUE TITLE
Include `nb_conda_kernels` in base JupyterHub conda environment

### ISSUE THREAD

**Issue by rsignell-usgs** [nds-org/esiphub#2]
If `nb_conda_kernels` is included in the base JupyterHub conda environment, then users can create custom environments and have them appear in the drop-down Kernel list in Jupyter.

**Comment by craig-willis** [comment]
I wasn't aware of this feature.  We'll  likely need to extend the default base image to support this, which shouldn't be a problem.

**Comment by craig-willis** [comment]
@rsignell-usgs I've created a custom image based on `jupyter/scipy-notebook` with `nb_conda_kernels` installed:

https://github.com/nds-org/esiphub/blob/master/dockerfiles/Dockerfile.scipy

Is there an easy test to confirm this is working?

**Comment by rsignell-usgs** [comment]
I restarted my server and now I can see my custom environment "rps" in the kernel list, so it's working!

![2018-04-14_16-59-38](https://user-images.githubusercontent.com/1872600/38772464-7c7e0080-4005-11e8-99c8-395143a78173.png)

Awesome!
