### ISSUE TITLE
Workshop Repo: please add

### ISSUE THREAD

**Issue by scgordon** [nds-org/esiphub#9]
I'm finished with technical requirements and have tested the repo on ESIPhub. While I have improvements to make, I think the MILES repo is ready to be added.

https://github.com/scgordon/MILES

**Comment by kmaull-ucar** [comment]
Can you add me as a contributor ...  there are a few cosmetic edits I'd
like to make.
K:M

**Comment by scgordon** [comment]
Happy to accept the help! Done.

**Comment by craig-willis** [comment]
How is this being added?

**Comment by scgordon** [comment]
Should have resolved. We're using the shared directory for ease of updating.
